version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4005:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-project:
    build: .
    image: conan736/simple-docker-node-app:1.0
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-volume:/data/db
  
  redis:
    image: redis

volumes:
  mongo-volume:
    external: false