version: "3"
services:
  nginx:
    ports:
      - "4005:80"

  node-project:
    build:
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=myusername
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myusername
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
