version: "3"
services:
  nginx:
    ports:
    - "80:80"

  node-project:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm run prod